### ISSUE TITLE
why ddpy.py line 99 self.action_gradient has -

### ISSUE THREAD

**Issue by jintw** [pemami4911/deep-rl#10]
why ddpy.py line 99 self.action_gradient has -

the corresponding op(4) in your blog don't have it

I can't understand..

**Comment by GoingMyWay** [comment]
My understanding is in the paper, the actor policy updating format it

![image](https://user-images.githubusercontent.com/9346460/42011571-88efd252-7ac6-11e8-83df-e9e89ae8eb60.png)

and since the `J` is the expected value and our target is to maximizing the `J`, so in 

```
self.unnormalized_actor_gradients = tf.gradients(
            self.scaled_out, self.network_params, -self.action_gradient)
        self.actor_gradients = list(map(lambda x: tf.div(x, self.batch_size), self.unnormalized_actor_gradients))
```

negating `self.action_gradient` is a good trick to minimizing the `J`.

In 
```
self.unnormalized_actor_gradients = tf.gradients(
            self.scaled_out, self.network_params, -self.action_gradient)
```
`-self.action_gradient` is the weight as in the paper


![image](https://user-images.githubusercontent.com/9346460/42011786-ac25ed96-7ac7-11e8-90c8-054646a51cf3.png)
 

Part A is `tf.gradients(self.scaled_out, self.network_params)` and part B is`-self.action_gradient`.
